blank_issues_enabled: false
contact_links:
  - name: "Do you have any specific doubts or want to contact maintainers?"
    url: mailto:kurian.bkk@gmail.com
    about: Contact the maintainers through our Open source channel